name: New Feature
description: Request a new feature to be added!
title: "[Featurre]: "
labels: ["enhancement", "triage"]
projects: ["CompilerErrorRBX/1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to tell us what you'd like to see in the game!
  - type: textarea
    id: what-would-you-like
    attributes:
      label: What would you like to see us add to Aftermath?
      placeholder: Please provide a detailed explanation of the feature you are interested in seeing. Pictures are much appreciated!
    validations:
      required: true
